# Generated by go2rpm 1.8.2
%bcond_without check
%global debug_package %{nil}

# https://github.com/josephlr/google-api-go-client
%global goipath         github.com/josephlr/google-api-go-client
Version:                0.86.1

%gometa -f

%global common_description %{expand:
Auto-generated Google APIs for Go.}

%global golicenses      LICENSE
%global godocs          docs examples AUTHORS CHANGES.md CODE_OF_CONDUCT.md\\\
                        CONTRIBUTORS GettingStarted.md\\\
                        README.md RELEASING.md SECURITY.md TODO testing.md

Name:           %{goname}
Release:        %autorelease
Summary:        Auto-generated Google APIs for Go

License:        BSD-3-Clause
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
find -name '*.go' | xargs sed -i \
    's|"google.golang.org/api|"github.com/josephlr/google-api-go-client|'
find -name '*.go' | xargs sed -i \
    's|"github.com/google/go-github/v42|"github.com/google/go-github|'

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
# Disable tests requiring authentication
for test in "TestNewTokenSource" \
            "TestNewClient_WithCredentialFile" \
            "TestNewClient_WithCredentialJSON" \
            "TestAPIs" \
; do
awk -i inplace '/^func.*'"$test"'\(/ { print; print "\tt.Skip(\"disabled failing test\")"; next}1' $(grep -rl $test)
done

%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
